//! JavaScript code generator
//!
//! Generates clean, modern JavaScript (ES6+) code from block graphs.

use super::{CodeContext, CodeGenerator, GeneratedCode, TargetLanguage, find_entry_block, is_data_block};
use crate::blocks::BlockData;
use crate::graph::ConnectionGraph;
use crate::types::{DataType, PortDirection, PortId};

/// JavaScript code generator
pub struct JavaScriptGenerator;

impl CodeGenerator for JavaScriptGenerator {
    fn generate(
        &self,
        blocks: &[BlockData],
        connections: &ConnectionGraph,
    ) -> GeneratedCode {
        let mut ctx = CodeContext::new(2);
        
        // Add file header
        ctx.add_raw_line(self.comment("Generated by 6IDE7"));
        ctx.add_raw_line(self.comment("Target: JavaScript ES6+"));
        ctx.add_raw_line("\"use strict\";".to_string());
        ctx.add_empty_line();
        
        // Generate main function
        ctx.add_line("async function main() {".to_string());
        ctx.push_indent();
        
        if blocks.is_empty() {
            ctx.add_line("// No blocks to execute".to_string());
        } else {
            // Find entry point
            if let Some(entry) = find_entry_block(blocks, connections) {
                self.generate_block_code(entry, blocks, connections, &mut ctx);
            } else {
                // Generate all blocks
                for block in blocks {
                    if is_data_block(block) {
                        self.generate_data_block(block, connections, &mut ctx);
                    }
                }
            }
        }
        
        ctx.pop_indent();
        ctx.add_line("}".to_string());
        ctx.add_empty_line();
        
        // Add entry point
        ctx.add_line("main().catch(console.error);".to_string());
        
        // Build final code
        let mut code_lines = Vec::new();
        
        // Add imports
        for imp in &ctx.imports {
            code_lines.push(imp.clone());
        }
        if !ctx.imports.is_empty() {
            code_lines.push(String::new());
        }
        
        // Add main code
        code_lines.extend(ctx.lines.clone());
        
        GeneratedCode {
            language: TargetLanguage::JavaScript,
            code: code_lines.join("\n"),
            entry_point: Some("main".to_string()),
            imports: ctx.imports.clone(),
            warnings: ctx.warnings.clone(),
        }
    }
    
    fn language(&self) -> TargetLanguage {
        TargetLanguage::JavaScript
    }
    
    fn comment(&self, text: &str) -> String {
        format!("// {}", text)
    }
    
    fn string_literal(&self, value: &str) -> String {
        let escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t");
        format!("\"{}\"", escaped)
    }
    
    fn number_literal(&self, value: &str, _is_float: bool) -> String {
        value.to_string()
    }
    
    fn bool_literal(&self, value: bool) -> String {
        if value { "true".to_string() } else { "false".to_string() }
    }
}

impl JavaScriptGenerator {
    /// Generate code for a specific block
    fn generate_block_code(
        &self,
        block: &BlockData,
        blocks: &[BlockData],
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        ctx.add_empty_line();
        ctx.add_line(self.comment(&format!("Block: {}", block.name)));
        
        match block.category.as_str() {
            "io" => self.generate_io_block(block, connections, ctx),
            "data" => self.generate_data_block(block, connections, ctx),
            "control" => self.generate_control_block(block, blocks, connections, ctx),
            "function" => self.generate_function_block(block, connections, ctx),
            "math" => self.generate_math_block(block, connections, ctx),
            "string" => self.generate_string_block(block, connections, ctx),
            _ => {
                ctx.add_warning(format!("Unknown block category: {}", block.category));
                ctx.add_line(format!("// Unknown block: {}", block.name));
            }
        }
    }
    
    /// Generate I/O block code
    fn generate_io_block(
        &self,
        block: &BlockData,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        match block.name.as_str() {
            "Print" => {
                let value = self.get_input_value(block, "value", connections, ctx);
                ctx.add_line(format!("console.log({});", value));
            }
            "Input" => {
                let prompt = self.get_input_value(block, "prompt", connections, ctx);
                let result_var = ctx.get_output_var(&block.id, "result");
                ctx.add_import("const readline = require('readline');".to_string());
                ctx.add_line(format!("const {} = await new Promise(resolve => {{", result_var));
                ctx.push_indent();
                ctx.add_line("const rl = readline.createInterface({ input: process.stdin, output: process.stdout });".to_string());
                ctx.add_line(format!("rl.question({}, answer => {{ rl.close(); resolve(answer); }});", prompt));
                ctx.pop_indent();
                ctx.add_line("});".to_string());
            }
            "Read File" => {
                let path = self.get_input_value(block, "path", connections, ctx);
                let content_var = ctx.get_output_var(&block.id, "content");
                ctx.add_import("const fs = require('fs/promises');".to_string());
                ctx.add_line(format!("const {} = await fs.readFile({}, 'utf-8');", content_var, path));
            }
            "Write File" => {
                let path = self.get_input_value(block, "path", connections, ctx);
                let content = self.get_input_value(block, "content", connections, ctx);
                ctx.add_import("const fs = require('fs/promises');".to_string());
                ctx.add_line(format!("await fs.writeFile({}, String({}));", path, content));
            }
            _ => {
                ctx.add_line(format!("// I/O block: {}", block.name));
            }
        }
    }
    
    /// Generate data block code
    fn generate_data_block(
        &self,
        block: &BlockData,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        match block.name.as_str() {
            "Variable" => {
                let value = self.get_input_value(block, "value", connections, ctx);
                let result_var = ctx.get_output_var(&block.id, "result");
                ctx.add_line(format!("let {} = {};", result_var, value));
            }
            "Constant" => {
                let result_var = ctx.get_output_var(&block.id, "value");
                ctx.add_line(format!("const {} = null; // TODO: Set value", result_var));
            }
            "Array" => {
                let items = self.get_input_value(block, "items", connections, ctx);
                let result_var = ctx.get_output_var(&block.id, "array");
                ctx.add_line(format!("const {} = [{}];", result_var, items));
            }
            "Get Item" => {
                let array = self.get_input_value(block, "array", connections, ctx);
                let index = self.get_input_value(block, "index", connections, ctx);
                let result_var = ctx.get_output_var(&block.id, "item");
                ctx.add_line(format!("const {} = {}[{}];", result_var, array, index));
            }
            _ => {
                ctx.add_line(format!("// Data block: {}", block.name));
            }
        }
    }
    
    /// Generate control flow block code
    fn generate_control_block(
        &self,
        block: &BlockData,
        _blocks: &[BlockData],
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        match block.name.as_str() {
            "If" => {
                let condition = self.get_input_value(block, "condition", connections, ctx);
                ctx.add_line(format!("if ({}) {{", condition));
                ctx.push_indent();
                ctx.add_line("// Then branch".to_string());
                ctx.pop_indent();
                ctx.add_line("} else {".to_string());
                ctx.push_indent();
                ctx.add_line("// Else branch".to_string());
                ctx.pop_indent();
                ctx.add_line("}".to_string());
            }
            "For Loop" => {
                let start = self.get_input_value(block, "start", connections, ctx);
                let end = self.get_input_value(block, "end", connections, ctx);
                let index_var = ctx.get_output_var(&block.id, "index");
                ctx.add_line(format!("for (let {} = {}; {} < {}; {}++) {{", index_var, start, index_var, end, index_var));
                ctx.push_indent();
                ctx.add_line("// Loop body".to_string());
                ctx.pop_indent();
                ctx.add_line("}".to_string());
            }
            "While Loop" => {
                let condition = self.get_input_value(block, "condition", connections, ctx);
                ctx.add_line(format!("while ({}) {{", condition));
                ctx.push_indent();
                ctx.add_line("// Loop body".to_string());
                ctx.pop_indent();
                ctx.add_line("}".to_string());
            }
            "For Each" => {
                let array = self.get_input_value(block, "array", connections, ctx);
                let item_var = ctx.get_output_var(&block.id, "item");
                ctx.add_line(format!("for (const {} of {}) {{", item_var, array));
                ctx.push_indent();
                ctx.add_line("// Loop body".to_string());
                ctx.pop_indent();
                ctx.add_line("}".to_string());
            }
            "Break" => {
                ctx.add_line("break;".to_string());
            }
            "Continue" => {
                ctx.add_line("continue;".to_string());
            }
            _ => {
                ctx.add_line(format!("// Control block: {}", block.name));
            }
        }
    }
    
    /// Generate function block code
    fn generate_function_block(
        &self,
        block: &BlockData,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        match block.name.as_str() {
            "Function" => {
                let params = self.get_input_value(block, "params", connections, ctx);
                ctx.add_line(format!("function myFunction({}) {{", params));
                ctx.push_indent();
                ctx.add_line("// Function body".to_string());
                ctx.add_line("return null;".to_string());
                ctx.pop_indent();
                ctx.add_line("}".to_string());
            }
            "Call" => {
                let func = self.get_input_value(block, "function", connections, ctx);
                let args = self.get_input_value(block, "args", connections, ctx);
                let result_var = ctx.get_output_var(&block.id, "result");
                ctx.add_line(format!("const {} = {}({});", result_var, func, args));
            }
            "Return" => {
                let value = self.get_input_value(block, "value", connections, ctx);
                ctx.add_line(format!("return {};", value));
            }
            _ => {
                ctx.add_line(format!("// Function block: {}", block.name));
            }
        }
    }
    
    /// Generate math block code
    fn generate_math_block(
        &self,
        block: &BlockData,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        let result_var = ctx.get_output_var(&block.id, "result");
        
        match block.name.as_str() {
            "Add" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} + {};", result_var, a, b));
            }
            "Subtract" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} - {};", result_var, a, b));
            }
            "Multiply" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} * {};", result_var, a, b));
            }
            "Divide" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} / {};", result_var, a, b));
            }
            "Modulo" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} % {};", result_var, a, b));
            }
            "Power" => {
                let base = self.get_input_value(block, "base", connections, ctx);
                let exp = self.get_input_value(block, "exp", connections, ctx);
                ctx.add_line(format!("const {} = Math.pow({}, {});", result_var, base, exp));
            }
            "Compare" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} === {};", result_var, a, b));
            }
            "Greater" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} > {};", result_var, a, b));
            }
            "Less" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} < {};", result_var, a, b));
            }
            "And" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} && {};", result_var, a, b));
            }
            "Or" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = {} || {};", result_var, a, b));
            }
            "Not" => {
                let value = self.get_input_value(block, "value", connections, ctx);
                ctx.add_line(format!("const {} = !{};", result_var, value));
            }
            _ => {
                ctx.add_line(format!("// Math block: {}", block.name));
            }
        }
    }
    
    /// Generate string block code
    fn generate_string_block(
        &self,
        block: &BlockData,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) {
        let result_var = ctx.get_output_var(&block.id, "result");
        
        match block.name.as_str() {
            "Concat" => {
                let a = self.get_input_value(block, "a", connections, ctx);
                let b = self.get_input_value(block, "b", connections, ctx);
                ctx.add_line(format!("const {} = String({}) + String({});", result_var, a, b));
            }
            "Format" => {
                // JavaScript doesn't have Python-style format, use template literals
                ctx.add_line(format!("const {} = ``; // TODO: Implement format", result_var));
            }
            "Split" => {
                let string = self.get_input_value(block, "string", connections, ctx);
                let delimiter = self.get_input_value(block, "delimiter", connections, ctx);
                ctx.add_line(format!("const {} = {}.split({});", result_var, string, delimiter));
            }
            "Join" => {
                let array = self.get_input_value(block, "array", connections, ctx);
                let delimiter = self.get_input_value(block, "delimiter", connections, ctx);
                ctx.add_line(format!("const {} = {}.join({});", result_var, delimiter, array));
            }
            "Length" => {
                let value = self.get_input_value(block, "value", connections, ctx);
                let length_var = ctx.get_output_var(&block.id, "length");
                ctx.add_line(format!("const {} = {}.length;", length_var, value));
            }
            _ => {
                ctx.add_line(format!("// String block: {}", block.name));
            }
        }
    }
    
    /// Get the value expression for an input port
    fn get_input_value(
        &self,
        block: &BlockData,
        port_id: &str,
        connections: &ConnectionGraph,
        ctx: &mut CodeContext,
    ) -> String {
        let port = PortId::new(&block.id, port_id);
        
        if let Some(conn) = connections.get_connection_to(&port) {
            let source_key = format!("{}:{}", conn.source.block_id, conn.source.port_id);
            if let Some(var) = ctx.var_names.get(&source_key) {
                return var.clone();
            }
            return format!("{}_{}", conn.source.block_id, conn.source.port_id);
        }
        
        if let Some(port_spec) = block.get_port(port_id) {
            if let Some(default) = &port_spec.default_value {
                return default.clone();
            }
            
            match &port_spec.data_type {
                DataType::Integer => "0".to_string(),
                DataType::Float => "0.0".to_string(),
                DataType::String => "\"\"".to_string(),
                DataType::Boolean => "false".to_string(),
                DataType::Any => "null".to_string(),
                _ => "null".to_string(),
            }
        } else {
            "null".to_string()
        }
    }
}
